export default {
  "login": "vkp27",
  "id": 88906754,
  "node_id": "MDQ6VXNlcjg4OTA2NzU0",
  "avatar_url": "https://avatars.githubusercontent.com/u/88906754?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/vkp27",
  "html_url": "https://github.com/vkp27",
  "followers_url": "https://api.github.com/users/vkp27/followers",
  "following_url": "https://api.github.com/users/vkp27/following{/other_user}",
  "gists_url": "https://api.github.com/users/vkp27/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/vkp27/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/vkp27/subscriptions",
  "organizations_url": "https://api.github.com/users/vkp27/orgs",
  "repos_url": "https://api.github.com/users/vkp27/repos",
  "events_url": "https://api.github.com/users/vkp27/events{/privacy}",
  "received_events_url": "https://api.github.com/users/vkp27/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Vaibhav Kumar Pandey",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": "Active Learner",
  "twitter_username": null,
  "public_repos": 5,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2021-08-13T19:45:38Z",
  "updated_at": "2022-04-19T07:28:37Z"
  };
  